# Generated by Django 2.2.4 on 2019-10-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energy',
            options={'ordering': ['resource']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterField(
            model_name='heightscale',
            name='height_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HeightScale_height_unit', to='scale.Unit'),
        ),
    ]
