# Generated by Django 2.2.4 on 2019-09-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('author', models.CharField(default='Cotev', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('author', models.CharField(default='Cotev', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('sketch_image', models.ImageField(upload_to='sketches/')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('cover_page', models.ImageField(upload_to='covers/')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author', models.CharField(default='Anonymous', max_length=100)),
                ('message', models.TextField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('page_title', models.CharField(max_length=100)),
                ('page', models.ImageField(upload_to='pages/')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Story')),
            ],
        ),
    ]
