# Generated by Django 2.2.4 on 2020-02-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('author', models.CharField(default='Cotev', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('subject', models.CharField(default='Subjet', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MakingOfItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('item_nb', models.PositiveIntegerField(unique=True)),
                ('making_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.MakingOf')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='sketch_image',
            field=models.ImageField(upload_to='blog/sketches/'),
        ),
        migrations.CreateModel(
            name='MakingOfFigure',
            fields=[
                ('makingofitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.MakingOfItem')),
                ('fig', models.ImageField(upload_to='blog/making_of')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.makingofitem',),
        ),
        migrations.CreateModel(
            name='MakingOfText',
            fields=[
                ('makingofitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.MakingOfItem')),
                ('text', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.makingofitem',),
        ),
    ]
