# Generated by Django 2.2.4 on 2020-02-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makingof',
            name='subject',
        ),
    ]
