# Generated by Django 2.2.4 on 2020-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_makingof_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingofitem',
            name='item_nb',
            field=models.PositiveIntegerField(),
        ),
    ]
