# Generated by Django 2.2.4 on 2020-02-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item', max_length=100)),
                ('author', models.CharField(default='Cotev', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('subjet', models.CharField(default='Subjet', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Item')),
                ('item_nb', models.PositiveIntegerField(unique=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Report')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.item',),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('reportitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.ReportItem')),
                ('fig', models.ImageField(upload_to='models/')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.reportitem',),
        ),
        migrations.CreateModel(
            name='ReportText',
            fields=[
                ('reportitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.ReportItem')),
                ('text', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('models.reportitem',),
        ),
    ]
