# Generated by Django 2.2.4 on 2020-02-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='subjet',
            new_name='subject',
        ),
    ]
