# Generated by Django 2.2.4 on 2020-02-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200221_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='subject',
        ),
    ]
